### PR TITLE
Fixed issue with push success messages being dropped

### PR DESCRIPTION
**Pull request by slindberg**

### CODE REVIEW

**Comment by rwjblue** [comment]
Good catch!

**Comment by rwjblue** [comment]
Just did `ember release && npm publish` on ember-waypoints ([commit here](https://github.com/rwjblue/ember-waypoints/commit/0e3a108474d18f62cf04c3525e5c9f34180cdc14) while locked to the commit containing this change ([see here](https://github.com/rwjblue/ember-waypoints/commit/cdbaa99a3fb0dcaf7b08234da473fa5cde862442)) and all went perfectly!

Mind publishing a 0.2.2 for this?

**Comment by slindberg** [comment]
Done.

**Comment by slindberg** [comment]
aw yiss.
screenshot 2015-04-14 09 29 40

**Pull request merged**
