### PR TITLE
Document as deprecated

### PR DESCRIPTION
**Pull request by lukemelia**
Per #77

### CODE REVIEW

**Comment by jelhan** [comment]
Per discussion in #77 I think `release-it` should be mentioned as alternative.

**Comment by rwwagner90** [comment]
@elwayman02 @jelhan would either of you like to write up something about using release-it? I am in favor of deprecating this.

**Comment by jelhan** [comment]
Similar to this PR or with more content? I can do the first one but don't have enough knowledge about this addon to write a migration guide or something alike.

**Comment by elwayman02** [comment]
I don't think a migration guide is necessary so much as to document what is necessary to onboard into release-it. The "migration" step would just be deleting the existing integration altogether and then adding the new stuff.

**Comment by rwwagner90** [comment]
Yeah, no migration guide necessary really, just suggesting how to use release-it and deferring to their docs.

**Comment by jelhan** [comment]
#78 adds a deprecation message and recommends release-it instead as discussed here.

**Pull request closed without merging**
