### PR TITLE
Add support for SemVer prereleases

### LINKED ISSUE #20: Support for prelease versions like 1.0.0-beta.1
See https://github.com/npm/node-semver#prerelease-identifiers

### PR DESCRIPTION
**Pull request by slindberg**
Closes #20

### CODE REVIEW

**Comment by slindberg** [comment]
@mmun This is implemented as you describe in [your comment](https://github.com/lytics/ember-cli-release/issues/20#issuecomment-157800888) on #20, with the exception that I did not include a `--prepatch` option since it's redundant and uncommon.

Ultimately I decided that [the situation I described](https://github.com/lytics/ember-cli-release/issues/20#issuecomment-157909666) is not a big deal, and certainly not worth holding back support for prereleases any longer.

**Comment by mmun** [comment]
Sweet! Looks great.

**Comment by rwjblue** [comment]
:+1: - LGTM

---

As an aside (this is unrelated to logic in this repo), it does seem slightly odd to me that `ember release --premajor beta` or `ember release --prerelease` starts at 0 (instead of 1).  Again, doesn't matter much, just surprised me that that was the semver packages incr result.

**Comment by slindberg** [comment]
@rwjblue that surprised me too, but only because I was used to the Ember convention of starting at 1. Do you know where that came from?  It looks like it goes all the way back to the `1.0.0-pre` days.

I debated changing it to start at 1 for consistency, because after all this addon is part of an opinionated framework that already seems to have an opinion on the subject. The downside is it's not vanilla SemVer, although it's such a minor thing that I can't imagine it really throwing off someone new to Ember.

Thoughts?

**Comment by rwjblue** [comment]
I'm 100% happy to follow the semver package here. It's pretty trivial to just specify the next version on the command line (likely what I would do anyways vs looking up the right --presomething command). 

TBH, I'm not sure where our convention of starting with beta.1 came from, but I vaguely feel like most non-ember related packages that I've seen do the same (could just be my own internal confirmation bias though).

**Comment by slindberg** [comment]
SGTM.

**Comment by mmun** [comment]
@rwjblue I totally agree. Some of the `semver` default behaviours are not intuitive.

**Pull request merged**
