### PR TITLE
Added a link to introduction video

### PR DESCRIPTION
**Pull request by taras**

### CODE REVIEW

**Comment by rwjblue** [comment]
I had to revert in https://github.com/lytics/ember-cli-release/pull/47 because the image looks pretty out of place.

**Comment by taras** [comment]
@rwjblue We're creating these videos to give people more information about  the addon. We have an `Introduction to ` video at every Global Ember Meetup. How can we make it look right?

**Comment by rwjblue** [comment]
@taras - The image itself that was shown was very blurry and gave no indication of what the picture was for in the readme.  Perhaps a little text, and having the splash image from the video (that has @slindberg's face and title slide) would be a better image than:

image

**Comment by taras** [comment]
Oh, I think something got screwed up. Let me fix that.

**Pull request merged**
